version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
      - image: postgres:9.6
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install NodeJS
          command: sudo apt-get update --quiet && sudo apt-get install --assume-yes nodejs
      - run:
          name: Install bundler
          command: gem install bundler --version 2.1.4
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: Database config
          command: cp config/database.yml.sample config/database.yml
      - run:
          name: Create Database
          command: bundle exec rake db:setup
      - run:
          name: Migrate DB
          command: bundle exec rake db:migrate
      - run:
          name: Create dot-env file
          command: echo FROM_ADDRESS='test@example.com' > .env
      - run:
          name: Test
          command: bundle exec rspec
